version: '3.8'
services:
  fumRabbit:
    image: rabbitmq:alpine
    expose:
      - 5672
    volumes:
      - './rabbitmq-volume:/var/lib/rabbitmq'

  fumlogger: 
    build: ./AppSrc/logger
    environment:
      - API_MODE=production

  
  fumPostgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: FumGeneral
    expose:
      - 5432
    volumes:
      - ./fum-general-postgres-volume:/var/lib/postgresql/data

  fumApi:
    build: path