version: '3.8'
services:
  fumRabbit:
    image: rabbitmq:alpine
    expose:
      - 5672
    volumes:
      - './rabbitmq-volume:/var/lib/rabbitmq'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 10

  fumlogger: 
    build: ./AppSrc/logger
    environment:
      - API_MODE=production
    depends_on:
      fumRabbit:
        condition: service_healthy


  fumGenralPostgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: FumGeneral
    expose:
      - 5432
    volumes:
      - ./fum-general-postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  fumgeneralapi:
    build: 
      context: ./AppSrc
      dockerfile: GenralApi.Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:80
    depends_on:
      fumGenralPostgres: 
        condition: service_healthy
      fumRabbit:
        condition: service_healthy

  fumgeneralgrpc:
    build: 
      context: ./AppSrc
      dockerfile: GeneralGrpc.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:80
    depends_on:
      fumGenralPostgres: 
        condition: service_healthy
      fumRabbit:
        condition: service_healthy
  
  fummaingateway:
    build: 
      context: ./AppSrc
      dockerfile: MainGateway/MainGateway/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - ASPNETCORE_URLS=http://*:5000
    
#  image: postgres:alpine
#     environment:
#       POSTGRES_PASSWORD: 1
#       POSTGRES_USER: postgres
#       POSTGRES_DB: FumGeneral
#     expose:
#       - 5432
#     volumes:
#       - ./fum-general-postgres-volume:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 10s
#       timeout: 5s
#       retries: 5


  fumCalculationsPostgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: FumCalculations
    expose:
      - 5432
    volumes:
      - ./fum-calculations-postgres-volume:/var/lib/postgresql/data

      

  fumcalculationapi:
    build: 
      context: ./AppSrc
      dockerfile: CalculationsApi.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://localhost:5000
