services:
  rabbit:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "4369:4369"
      - "5671:5671"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "./rabbitmq:/var/lib/rabbitmq"